name: Deploy HTML site to GitHub Pages

on:
  push:
    branches:
      - main  # запуск workflow при пуше в ветку main

jobs:
  deploy:
    # Используем виртуальную машину Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      # Шаг 2: Собираем папку dist с HTML и CSS
      - name: Собираем HTML и CSS
        run: |
          mkdir dist
          cp index.html dist/
          cp style.css dist/

      # Шаг 3: Деплой на GitHub Pages
      - name: Деплой на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # встроенный секретный токен GitHub
          publish_dir: ./dist                        # папка, которую нужно опубликовать
